import cv2
import pytesseract
import os
import numpy
import requests
import time

# Config
VIDEO_DIR = "/root/videos"
VIDEO_FILE = "2608011038.mp4"
VIDEO_PATH = os.path.join(VIDEO_DIR, VIDEO_FILE)
START_FRAME_NUMBER = (20*60*60)+(31.5*60)
FRAME_COUNT = 1

# In-Raid UI

COMPASS_SUBREGION = (675, 16, 550, 24)
COMPASS_BEARING_VALUE_SUBREGION = (936, 16, 48, 24)
COMPASS_OBJECTIVES_SUBREGION = (675, 40, 550, 32)
COMPASS_TEXT_SUBREGION = (783, 73, 371, 26)
MATCH_TIMER_SUBREGION = (930, 100, 60, 24)
AUTOMATIC_EXTRACTION_TIMER_SUBREGION = (810, 103, 299, 18)
RETURN_POINT_SHUTDOWN_NOTICE_REGION = (712, 184, 503, 88)

QUICKWHEEL_BOUNDING_BOX = (649, 230, 622, 620)
QUICKWHEEL_TEXT_SUBREGION = (883, 520, 154, 32)

FRAME_RATE_COUNTER_SUBREGION = (1866, 0, 54, 21)

LOCATION_TEXT_SUBREGION = (22, 389, 392, 87)

XP_LOGS_SUBREGION = (23, 308, 355, 118)

PLAYER_PROXIMITY_VOICE_SUBREGION = (21, 592, 288, 39)

PLAYER_CHAT_SUBREGION = (36, 704, 448, 70)

PLAYER_2_BOUNDING_BOX = (39, 876, 271, 68)
PLAYER_2_COLOR_SUBREGION = (45, 895, 6, 20)

PLAYER_1_BOUNDING_BOX = (40, 944, 270, 90)

PLAYER_1_VOICE_ICON_SUBREGION = (268, 944, 20, 19)

PLAYER_1_SHIELD_NW_POINT = (40, 994)
PLAYER_1_SHIELD_NE_POINT = (309, 966)
PLAYER_1_SHIELD_SE_POINT = (309, 981)
PLAYER_1_SHIELD_SW_POINT = (40, 1011)
PLAYER_1_SHIELD_BOUNDING_BOX = (40, 966, 269, 46)
PLAYER_1_SHIELD_SLICE_SUBREGION = (4, 20, 261, 1)
# src_points = numpy.float32([PLAYER_1_SHIELD_NW_POINT, PLAYER_1_SHIELD_NE_POINT, PLAYER_1_SHIELD_SW_POINT, PLAYER_1_SHIELD_SE_POINT]) 
# dst_points = numpy.float32([[0, 0], [w, 0], [0, h], [w, h]])
# M = cv2.getPerspectiveTransform(src_points, dst_points)
# unwarped_image = cv2.warpPerspective(frame, M, (w, h))

PLAYER_1_HEALTH_NW_POINT = (40, 1016)
PLAYER_1_HEALTH_NE_POINT = (309, 986)
PLAYER_1_HEALTH_SE_POINT = (309, 1001)
PLAYER_1_HEALTH_SW_POINT = (40, 1033)
PLAYER_1_HEALTH_BOUNDING_BOX = (40, 986, 269, 46)
PLAYER_1_HEALTH_SLICE_SUBREGION = (4, 20, 261, 1)
# src_points = numpy.float32([PLAYER_1_HEALTH_NW_POINT, PLAYER_1_HEALTH_NE_POINT, PLAYER_1_HEALTH_SW_POINT, PLAYER_1_HEALTH_SE_POINT]) 
# dst_points = numpy.float32([[0, 0], [w, 0], [0, h], [w, h]])
# M = cv2.getPerspectiveTransform(src_points, dst_points)
# unwarped_image = cv2.warpPerspective(frame, M, (w, h))

OVER_ENCUMBERED_ICON_REGION = (946, 936, 28, 24)

STAMINA_BAR_SUBREGION = (857, 968, 206, 16)
STAMINA_BAR_SLICE_SUBREGION = (3, 7, 200, 1)

PATCH_SERVER_LOBBY_REGION = (1731, 1060, 160, 20)

RELOAD_INDICATOR_SUBREGION = (940, 520, 40, 40)

QUICK_ITEM_1_SUBREGION = (1536, 909, 64, 92)
QUICK_ITEM_2_SUBREGION = (1608, 914, 64, 94)

UNSELECTED_SECONDARY_WEAPON_BOUNDING_BOX = (1680, 980, 200, 55)
SELECTED_PRIMARY_WEAPON_BOUNDING_BOX = (1680, 883, 200, 112)
SELECTED_PRIMARY_WEAPON_CURRENT_AMMO_SUBREGION = (1698, 924, 53, 28)
SELECTED_PRIMARY_WEAPON_RESERVE_AMMO_SUBREGION = (1720, 952, 32, 17)

FLASHLIGHT_TOOL_TIP_REGION = (1743, 821, 140, 37)
UNARMED_TOOL_TIP_REGION = (1743, 784, 140, 37)

DIALOGUE_CAPTION_SUBREGION = (587, 985, 751, 95)

RECHARGE_OWN_SHIELD_SUBREGION = (1176, 678, 219, 32)
RECHARGE_OTHER_SHIELD_SUBREGION = (1176, 726, 233, 32)

PLAYER_ZONE_BOUNDING_BOX = (469, 398, 980, 682)

# Looting UI

LOOTING_INVENTORY_NAVIGATION_SUBREGION = (634, 23, 648, 42)
LOOTING_INVENTORY_LOADOUT_DETAILS_SUBREGION = (661, 158, 306, 69)
LOOTING_EQUIPMENT_AUGMENT_SUBREGION = (661, 295, 146, 98)
LOOTING_EQUIPMENT_SHIELD_SUBREGION = (821, 295, 146, 98)
LOOTING_EQUIPMENT_PRIMARY_WEAPON_SUBREGION = (661, 415, 306, 202)
LOOTING_EQUIPMENT_SECONDARY_WEAPON_SUBREGION = (661, 631, 306, 202)
LOOTING_BACKPACK_LABEL_SUBREGION = (1013, 255, 156, 17)
LOOTING_BACKPACK_BOUNDING_BOX = (1013, 295, 410, 514)
LOOTING_QUICK_USE_LABEL_SUBREGION = (1473, 255, 142, 17)
LOOTING_QUICK_USE_BOUNDING_BOX = (1473, 295, 306, 202)
LOOTING_AUGMENTED_SLOTS_LABEL_SUBREGION = (1473, 527, 218, 17)
LOOTING_AUGMENTED_SLOTS_BOUNDING_BOX = (1473, 567, 306, 98)
LOOTING_SAFE_POCKET_LABEL_SUBREGION = (1473, 695, 155, 17)
LOOTING_SAFE_POCKET_BOUNDING_BOX = (1473, 735, 306, 98)
LOOTING_CONTAINER_BOUNDING_BOX = (141, 295, 410, 410)
LOOTING_KEYBINDS_BOUNDING_BOX = (51, 1017, 764, 34)

LOOTING_SALVAGE_BOUNDING_BOX = (570, 313, 780, 454)

# Map UI

MAP_LEGEND_BOUNDING_BOX = (1506, 128, 350, 815)

# Open video file and navigate to desired start frame
capture = cv2.VideoCapture(VIDEO_PATH)

if not capture.isOpened():
    raise FileNotFoundError(f"Could not open video file: {video_path}")

# Set the frame position
capture.set(cv2.CAP_PROP_POS_FRAMES, START_FRAME_NUMBER)

results = []

for offset in range(FRAME_COUNT):
    ret, frame = capture.read()
    if not ret:
        raise ValueError(f"Could not read frame {START_FRAME_NUMBER} from video.")

    # Draw In-Raid UI subregions
    # cv2.rectangle(frame, COMPASS_SUBREGION[:2], (COMPASS_SUBREGION[0] + COMPASS_SUBREGION[2], COMPASS_SUBREGION[1] + COMPASS_SUBREGION[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, COMPASS_BEARING_VALUE_SUBREGION[:2], (COMPASS_BEARING_VALUE_SUBREGION[0] + COMPASS_BEARING_VALUE_SUBREGION[2], COMPASS_BEARING_VALUE_SUBREGION[1] + COMPASS_BEARING_VALUE_SUBREGION[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, COMPASS_OBJECTIVES_SUBREGION[:2], (COMPASS_OBJECTIVES_SUBREGION[0] + COMPASS_OBJECTIVES_SUBREGION[2], COMPASS_OBJECTIVES_SUBREGION[1] + COMPASS_OBJECTIVES_SUBREGION[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, COMPASS_TEXT_SUBREGION[:2], (COMPASS_TEXT_SUBREGION[0] + COMPASS_TEXT_SUBREGION[2], COMPASS_TEXT_SUBREGION[1] + COMPASS_TEXT_SUBREGION[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, MATCH_TIMER_SUBREGION[:2], (MATCH_TIMER_SUBREGION[0] + MATCH_TIMER_SUBREGION[2], MATCH_TIMER_SUBREGION[1] + MATCH_TIMER_SUBREGION[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, AUTOMATIC_EXTRACTION_TIMER_SUBREGION[:2], (AUTOMATIC_EXTRACTION_TIMER_SUBREGION[0] + AUTOMATIC_EXTRACTION_TIMER_SUBREGION[2], AUTOMATIC_EXTRACTION_TIMER_SUBREGION[1] + AUTOMATIC_EXTRACTION_TIMER_SUBREGION[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, RETURN_POINT_SHUTDOWN_NOTICE_REGION[:2], (RETURN_POINT_SHUTDOWN_NOTICE_REGION[0] + RETURN_POINT_SHUTDOWN_NOTICE_REGION[2], RETURN_POINT_SHUTDOWN_NOTICE_REGION[1] + RETURN_POINT_SHUTDOWN_NOTICE_REGION[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, QUICKWHEEL_BOUNDING_BOX[:2], (QUICKWHEEL_BOUNDING_BOX[0] + QUICKWHEEL_BOUNDING_BOX[2], QUICKWHEEL_BOUNDING_BOX[1] + QUICKWHEEL_BOUNDING_BOX[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, QUICKWHEEL_TEXT_SUBREGION[:2], (QUICKWHEEL_TEXT_SUBREGION[0] + QUICKWHEEL_TEXT_SUBREGION[2], QUICKWHEEL_TEXT_SUBREGION[1] + QUICKWHEEL_TEXT_SUBREGION[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, FRAME_RATE_COUNTER_SUBREGION[:2], (FRAME_RATE_COUNTER_SUBREGION[0] + FRAME_RATE_COUNTER_SUBREGION[2], FRAME_RATE_COUNTER_SUBREGION[1] + FRAME_RATE_COUNTER_SUBREGION[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, LOCATION_TEXT_SUBREGION[:2], (LOCATION_TEXT_SUBREGION[0] + LOCATION_TEXT_SUBREGION[2], LOCATION_TEXT_SUBREGION[1] + LOCATION_TEXT_SUBREGION[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, XP_LOGS_SUBREGION[:2], (XP_LOGS_SUBREGION[0] + XP_LOGS_SUBREGION[2], XP_LOGS_SUBREGION[1] + XP_LOGS_SUBREGION[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, PLAYER_PROXIMITY_VOICE_SUBREGION[:2], (PLAYER_PROXIMITY_VOICE_SUBREGION[0] + PLAYER_PROXIMITY_VOICE_SUBREGION[2], PLAYER_PROXIMITY_VOICE_SUBREGION[1] + PLAYER_PROXIMITY_VOICE_SUBREGION[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, PLAYER_CHAT_SUBREGION[:2], (PLAYER_CHAT_SUBREGION[0] + PLAYER_CHAT_SUBREGION[2], PLAYER_CHAT_SUBREGION[1] + PLAYER_CHAT_SUBREGION[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, PLAYER_2_BOUNDING_BOX[:2], (PLAYER_2_BOUNDING_BOX[0] + PLAYER_2_BOUNDING_BOX[2], PLAYER_2_BOUNDING_BOX[1] + PLAYER_2_BOUNDING_BOX[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, PLAYER_1_BOUNDING_BOX[:2], (PLAYER_1_BOUNDING_BOX[0] + PLAYER_1_BOUNDING_BOX[2], PLAYER_1_BOUNDING_BOX[1] + PLAYER_1_BOUNDING_BOX[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, PLAYER_1_VOICE_ICON_SUBREGION[:2], (PLAYER_1_VOICE_ICON_SUBREGION[0] + PLAYER_1_VOICE_ICON_SUBREGION[2], PLAYER_1_VOICE_ICON_SUBREGION[1] + PLAYER_1_VOICE_ICON_SUBREGION[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, PLAYER_1_SHIELD_BOUNDING_BOX[:2], (PLAYER_1_SHIELD_BOUNDING_BOX[0] + PLAYER_1_SHIELD_BOUNDING_BOX[2], PLAYER_1_SHIELD_BOUNDING_BOX[1] + PLAYER_1_SHIELD_BOUNDING_BOX[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, PLAYER_1_HEALTH_BOUNDING_BOX[:2], (PLAYER_1_HEALTH_BOUNDING_BOX[0] + PLAYER_1_HEALTH_BOUNDING_BOX[2], PLAYER_1_HEALTH_BOUNDING_BOX[1] + PLAYER_1_HEALTH_BOUNDING_BOX[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, OVER_ENCUMBERED_ICON_REGION[:2], (OVER_ENCUMBERED_ICON_REGION[0] + OVER_ENCUMBERED_ICON_REGION[2], OVER_ENCUMBERED_ICON_REGION[1] + OVER_ENCUMBERED_ICON_REGION[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, STAMINA_BAR_SUBREGION[:2], (STAMINA_BAR_SUBREGION[0] + STAMINA_BAR_SUBREGION[2], STAMINA_BAR_SUBREGION[1] + STAMINA_BAR_SUBREGION[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, PATCH_SERVER_LOBBY_REGION[:2], (PATCH_SERVER_LOBBY_REGION[0] + PATCH_SERVER_LOBBY_REGION[2], PATCH_SERVER_LOBBY_REGION[1] + PATCH_SERVER_LOBBY_REGION[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, RELOAD_INDICATOR_SUBREGION[:2], (RELOAD_INDICATOR_SUBREGION[0] + RELOAD_INDICATOR_SUBREGION[2], RELOAD_INDICATOR_SUBREGION[1] + RELOAD_INDICATOR_SUBREGION[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, QUICK_ITEM_1_SUBREGION[:2], (QUICK_ITEM_1_SUBREGION[0] + QUICK_ITEM_1_SUBREGION[2], QUICK_ITEM_1_SUBREGION[1] + QUICK_ITEM_1_SUBREGION[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, QUICK_ITEM_2_SUBREGION[:2], (QUICK_ITEM_2_SUBREGION[0] + QUICK_ITEM_2_SUBREGION[2], QUICK_ITEM_2_SUBREGION[1] + QUICK_ITEM_2_SUBREGION[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, UNSELECTED_SECONDARY_WEAPON_BOUNDING_BOX[:2], (UNSELECTED_SECONDARY_WEAPON_BOUNDING_BOX[0] + UNSELECTED_SECONDARY_WEAPON_BOUNDING_BOX[2], UNSELECTED_SECONDARY_WEAPON_BOUNDING_BOX[1] + UNSELECTED_SECONDARY_WEAPON_BOUNDING_BOX[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, SELECTED_PRIMARY_WEAPON_BOUNDING_BOX[:2], (SELECTED_PRIMARY_WEAPON_BOUNDING_BOX[0] + SELECTED_PRIMARY_WEAPON_BOUNDING_BOX[2], SELECTED_PRIMARY_WEAPON_BOUNDING_BOX[1] + SELECTED_PRIMARY_WEAPON_BOUNDING_BOX[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, SELECTED_PRIMARY_WEAPON_CURRENT_AMMO_SUBREGION[:2], (SELECTED_PRIMARY_WEAPON_CURRENT_AMMO_SUBREGION[0] + SELECTED_PRIMARY_WEAPON_CURRENT_AMMO_SUBREGION[2], SELECTED_PRIMARY_WEAPON_CURRENT_AMMO_SUBREGION[1] + SELECTED_PRIMARY_WEAPON_CURRENT_AMMO_SUBREGION[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, SELECTED_PRIMARY_WEAPON_RESERVE_AMMO_SUBREGION[:2], (SELECTED_PRIMARY_WEAPON_RESERVE_AMMO_SUBREGION[0] + SELECTED_PRIMARY_WEAPON_RESERVE_AMMO_SUBREGION[2], SELECTED_PRIMARY_WEAPON_RESERVE_AMMO_SUBREGION[1] + SELECTED_PRIMARY_WEAPON_RESERVE_AMMO_SUBREGION[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, FLASHLIGHT_TOOL_TIP_REGION[:2], (FLASHLIGHT_TOOL_TIP_REGION[0] + FLASHLIGHT_TOOL_TIP_REGION[2], FLASHLIGHT_TOOL_TIP_REGION[1] + FLASHLIGHT_TOOL_TIP_REGION[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, UNARMED_TOOL_TIP_REGION[:2], (UNARMED_TOOL_TIP_REGION[0] + UNARMED_TOOL_TIP_REGION[2], UNARMED_TOOL_TIP_REGION[1] + UNARMED_TOOL_TIP_REGION[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, DIALOGUE_CAPTION_SUBREGION[:2], (DIALOGUE_CAPTION_SUBREGION[0] + DIALOGUE_CAPTION_SUBREGION[2], DIALOGUE_CAPTION_SUBREGION[1] + DIALOGUE_CAPTION_SUBREGION[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, RECHARGE_OWN_SHIELD_SUBREGION[:2], (RECHARGE_OWN_SHIELD_SUBREGION[0] + RECHARGE_OWN_SHIELD_SUBREGION[2], RECHARGE_OWN_SHIELD_SUBREGION[1] + RECHARGE_OWN_SHIELD_SUBREGION[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, RECHARGE_OTHER_SHIELD_SUBREGION[:2], (RECHARGE_OTHER_SHIELD_SUBREGION[0] + RECHARGE_OTHER_SHIELD_SUBREGION[2], RECHARGE_OTHER_SHIELD_SUBREGION[1] + RECHARGE_OTHER_SHIELD_SUBREGION[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, PLAYER_ZONE_BOUNDING_BOX[:2], (PLAYER_ZONE_BOUNDING_BOX[0] + PLAYER_ZONE_BOUNDING_BOX[2], PLAYER_ZONE_BOUNDING_BOX[1] + PLAYER_ZONE_BOUNDING_BOX[3]), (0, 0, 255), 1)

    # Draw Looting UI subregions
    # cv2.rectangle(frame, LOOTING_INVENTORY_NAVIGATION_SUBREGION[:2], (LOOTING_INVENTORY_NAVIGATION_SUBREGION[0] + LOOTING_INVENTORY_NAVIGATION_SUBREGION[2], LOOTING_INVENTORY_NAVIGATION_SUBREGION[1] + LOOTING_INVENTORY_NAVIGATION_SUBREGION[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, LOOTING_INVENTORY_LOADOUT_DETAILS_SUBREGION[:2], (LOOTING_INVENTORY_LOADOUT_DETAILS_SUBREGION[0] + LOOTING_INVENTORY_LOADOUT_DETAILS_SUBREGION[2], LOOTING_INVENTORY_LOADOUT_DETAILS_SUBREGION[1] + LOOTING_INVENTORY_LOADOUT_DETAILS_SUBREGION[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, LOOTING_EQUIPMENT_AUGMENT_SUBREGION[:2], (LOOTING_EQUIPMENT_AUGMENT_SUBREGION[0] + LOOTING_EQUIPMENT_AUGMENT_SUBREGION[2], LOOTING_EQUIPMENT_AUGMENT_SUBREGION[1] + LOOTING_EQUIPMENT_AUGMENT_SUBREGION[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, LOOTING_EQUIPMENT_SHIELD_SUBREGION[:2], (LOOTING_EQUIPMENT_SHIELD_SUBREGION[0] + LOOTING_EQUIPMENT_SHIELD_SUBREGION[2], LOOTING_EQUIPMENT_SHIELD_SUBREGION[1] + LOOTING_EQUIPMENT_SHIELD_SUBREGION[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, LOOTING_EQUIPMENT_PRIMARY_WEAPON_SUBREGION[:2], (LOOTING_EQUIPMENT_PRIMARY_WEAPON_SUBREGION[0] + LOOTING_EQUIPMENT_PRIMARY_WEAPON_SUBREGION[2], LOOTING_EQUIPMENT_PRIMARY_WEAPON_SUBREGION[1] + LOOTING_EQUIPMENT_PRIMARY_WEAPON_SUBREGION[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, LOOTING_EQUIPMENT_SECONDARY_WEAPON_SUBREGION[:2], (LOOTING_EQUIPMENT_SECONDARY_WEAPON_SUBREGION[0] + LOOTING_EQUIPMENT_SECONDARY_WEAPON_SUBREGION[2], LOOTING_EQUIPMENT_SECONDARY_WEAPON_SUBREGION[1] + LOOTING_EQUIPMENT_SECONDARY_WEAPON_SUBREGION[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, LOOTING_BACKPACK_LABEL_SUBREGION[:2], (LOOTING_BACKPACK_LABEL_SUBREGION[0] + LOOTING_BACKPACK_LABEL_SUBREGION[2], LOOTING_BACKPACK_LABEL_SUBREGION[1] + LOOTING_BACKPACK_LABEL_SUBREGION[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, LOOTING_BACKPACK_BOUNDING_BOX[:2], (LOOTING_BACKPACK_BOUNDING_BOX[0] + LOOTING_BACKPACK_BOUNDING_BOX[2], LOOTING_BACKPACK_BOUNDING_BOX[1] + LOOTING_BACKPACK_BOUNDING_BOX[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, LOOTING_QUICK_USE_LABEL_SUBREGION[:2], (LOOTING_QUICK_USE_LABEL_SUBREGION[0] + LOOTING_QUICK_USE_LABEL_SUBREGION[2], LOOTING_QUICK_USE_LABEL_SUBREGION[1] + LOOTING_QUICK_USE_LABEL_SUBREGION[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, LOOTING_QUICK_USE_BOUNDING_BOX[:2], (LOOTING_QUICK_USE_BOUNDING_BOX[0] + LOOTING_QUICK_USE_BOUNDING_BOX[2], LOOTING_QUICK_USE_BOUNDING_BOX[1] + LOOTING_QUICK_USE_BOUNDING_BOX[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, LOOTING_AUGMENTED_SLOTS_LABEL_SUBREGION[:2], (LOOTING_AUGMENTED_SLOTS_LABEL_SUBREGION[0] + LOOTING_AUGMENTED_SLOTS_LABEL_SUBREGION[2], LOOTING_AUGMENTED_SLOTS_LABEL_SUBREGION[1] + LOOTING_AUGMENTED_SLOTS_LABEL_SUBREGION[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, LOOTING_AUGMENTED_SLOTS_BOUNDING_BOX[:2], (LOOTING_AUGMENTED_SLOTS_BOUNDING_BOX[0] + LOOTING_AUGMENTED_SLOTS_BOUNDING_BOX[2], LOOTING_AUGMENTED_SLOTS_BOUNDING_BOX[1] + LOOTING_AUGMENTED_SLOTS_BOUNDING_BOX[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, LOOTING_SAFE_POCKET_LABEL_SUBREGION[:2], (LOOTING_SAFE_POCKET_LABEL_SUBREGION[0] + LOOTING_SAFE_POCKET_LABEL_SUBREGION[2], LOOTING_SAFE_POCKET_LABEL_SUBREGION[1] + LOOTING_SAFE_POCKET_LABEL_SUBREGION[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, LOOTING_SAFE_POCKET_BOUNDING_BOX[:2], (LOOTING_SAFE_POCKET_BOUNDING_BOX[0] + LOOTING_SAFE_POCKET_BOUNDING_BOX[2], LOOTING_SAFE_POCKET_BOUNDING_BOX[1] + LOOTING_SAFE_POCKET_BOUNDING_BOX[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, LOOTING_CONTAINER_BOUNDING_BOX[:2], (LOOTING_CONTAINER_BOUNDING_BOX[0] + LOOTING_CONTAINER_BOUNDING_BOX[2], LOOTING_CONTAINER_BOUNDING_BOX[1] + LOOTING_CONTAINER_BOUNDING_BOX[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, LOOTING_KEYBINDS_BOUNDING_BOX[:2], (LOOTING_KEYBINDS_BOUNDING_BOX[0] + LOOTING_KEYBINDS_BOUNDING_BOX[2], LOOTING_KEYBINDS_BOUNDING_BOX[1] + LOOTING_KEYBINDS_BOUNDING_BOX[3]), (0, 0, 255), 1)
    # cv2.rectangle(frame, LOOTING_SALVAGE_BOUNDING_BOX[:2], (LOOTING_SALVAGE_BOUNDING_BOX[0] + LOOTING_SALVAGE_BOUNDING_BOX[2], LOOTING_SALVAGE_BOUNDING_BOX[1] + LOOTING_SALVAGE_BOUNDING_BOX[3]), (0, 0, 255), 1)

    # Draw Map UI subregions
    # cv2.rectangle(frame, MAP_LEGEND_BOUNDING_BOX[:2], (MAP_LEGEND_BOUNDING_BOX[0] + MAP_LEGEND_BOUNDING_BOX[2], MAP_LEGEND_BOUNDING_BOX[1] + MAP_LEGEND_BOUNDING_BOX[3]), (0, 0, 255), 1)

    cv2.imwrite("frame.jpg", frame)

    # Extract region of interest (ROI)
    x, y, w, h = PLAYER_ZONE_BOUNDING_BOX
    roi = frame[y:y + h, x:x + w]

    # Stamina calculation

    # slice_roi = roi[STAMINA_BAR_SLICE_SUBREGION[1]:STAMINA_BAR_SLICE_SUBREGION[1] + STAMINA_BAR_SLICE_SUBREGION[3], STAMINA_BAR_SLICE_SUBREGION[0]:STAMINA_BAR_SLICE_SUBREGION[0] + STAMINA_BAR_SLICE_SUBREGION[2]]
    # slice_values = []
    # for pixel in slice_roi[0]:
    #     white = [255, 255, 255]
    #     distance = abs(pixel - white).sum()
    #     if distance < 100:
    #         slice_values.append("W")
    #     else:
    #         slice_values.append("X")

    # stamina_string = "".join(slice_values)
    # print("Stamina:", stamina_string)
    # stamina_value = stamina_string.count("W")
    # print(f"White pixels in stamina bar: {stamina_value}")

    # Shield calculation

    # src_points = numpy.float32([PLAYER_1_SHIELD_NW_POINT, PLAYER_1_SHIELD_NE_POINT, PLAYER_1_SHIELD_SW_POINT, PLAYER_1_SHIELD_SE_POINT]) 
    # dst_points = numpy.float32([[0, 0], [w, 0], [0, h], [w, h]])
    # M = cv2.getPerspectiveTransform(src_points, dst_points)
    # unwarped_image = cv2.warpPerspective(frame, M, (w, h))

    # # calculate the numerical value of the shield 
    # slice_roi = unwarped_image[PLAYER_1_SHIELD_SLICE_SUBREGION[1]:PLAYER_1_SHIELD_SLICE_SUBREGION[1] + PLAYER_1_SHIELD_SLICE_SUBREGION[3], PLAYER_1_SHIELD_SLICE_SUBREGION[0]:PLAYER_1_SHIELD_SLICE_SUBREGION[0] + PLAYER_1_SHIELD_SLICE_SUBREGION[2]]
    # slice_values = []
    # for pixel in slice_roi[0]:
    #     blue = [167, 150, 63]
    #     red = [79, 77, 213]
    #     yellow = [54, 164, 205]
    #     black = [89, 81, 81]

    #     blue_delta = abs(pixel - blue).sum()
    #     red_delta = abs(pixel - red).sum()
    #     yellow_delta = abs(pixel - yellow).sum()
    #     black_delta = abs(pixel - black).sum()

    #     min_diff = min(blue_delta, red_delta, yellow_delta, black_delta)

    #     if (blue_delta == min_diff).all():
    #         slice_values.append("B")
    #     elif (red_delta == min_diff).all():
    #         slice_values.append("R")
    #     elif (yellow_delta == min_diff).all():
    #         slice_values.append("Y")
    #     elif (black_delta == min_diff).all():
    #         slice_values.append("X")
    #     else:
    #         print("No shield pixel detected")

    # shield_string = "".join(slice_values)
    # print("Shield:", shield_string)

    # # Count number of B, R, Y in shield value
    # num_blue = shield_string.count("B")
    # num_red = shield_string.count("R")
    # num_yellow = shield_string.count("Y")

    # # Count the number of Xs at the end of the string
    # num_black = len(shield_string) - len(shield_string.rstrip("X"))
    # print(f"Blue: {num_blue}, Red: {num_red}, Yellow: {num_yellow}, Black from end: {num_black}")

    # Health calculation

    # src_points = numpy.float32([PLAYER_1_HEALTH_NW_POINT, PLAYER_1_HEALTH_NE_POINT, PLAYER_1_HEALTH_SW_POINT, PLAYER_1_HEALTH_SE_POINT]) 
    # dst_points = numpy.float32([[0, 0], [w, 0], [0, h], [w, h]])
    # M = cv2.getPerspectiveTransform(src_points, dst_points)
    # unwarped_image = cv2.warpPerspective(frame, M, (w, h))

    # # calculate the numerical value of the health 
    # slice_roi = unwarped_image[PLAYER_1_HEALTH_SLICE_SUBREGION[1]:PLAYER_1_HEALTH_SLICE_SUBREGION[1] + PLAYER_1_HEALTH_SLICE_SUBREGION[3], PLAYER_1_HEALTH_SLICE_SUBREGION[0]:PLAYER_1_HEALTH_SLICE_SUBREGION[0] + PLAYER_1_HEALTH_SLICE_SUBREGION[2]]
    # slice_values = []
    # for pixel in slice_roi[0]:
    #     white = [255, 255, 255]
    #     distance = abs(pixel - white).sum()
    #     if distance < 100:
    #         slice_values.append("W")
    #     else:
    #         slice_values.append("X")

    # health_string = "".join(slice_values)
    # print("Health:", health_string)
    # health_value = health_string.count("W")
    # print(f"White pixels in health bar: {health_value}")

    cv2.imwrite("roi.jpg", roi)

    _, img_encoded = cv2.imencode('.jpg', roi)

    # Send it to the OCR API
    files = {"file": ("frame.jpg", img_encoded.tobytes(), "image/jpeg")}
    response = requests.post(OCR_URL, files=files)

    # Parse the JSON response
    if response.status_code == 200:
        data = response.json()
        # results.append(data["results"])
        for item in data["results"]:
            results.append(item["text"])
    else:
        print("❌ Error:", response.text)
    
    # print(START_FRAME_NUMBER + offset)
    # time.sleep(0.5)

capture.release()
print(results)

# Preprocess ROI for OCR
# gray = cv2.cvtColor(roi, cv2.COLOR_BGR2GRAY)

# _, threshold = cv2.threshold(gray, 128, 255, cv2.THRESH_TOZERO_INV)
# threshold = cv2.adaptiveThreshold(gray, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 3, 10)

# 2x scale
# scaled = cv2.resize(gray, None, fx=2.0, fy=2.0, interpolation=cv2.INTER_CUBIC)
# cv2.imwrite("scaled.jpg", scaled)

# result = reader.readtext(scaled)
# print(result)

# clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
# gray = clahe.apply(gray)

# OCR on the region
# text = pytesseract.image_to_string(threshold, config=custom_config)
# print(text)

# boxes = pytesseract.image_to_boxes(threshold, config=custom_config)
# for b in boxes.splitlines():
#     char, x1, y1, x2, y2, _ = b.split()
#     x1, y1, x2, y2 = int(x1), int(y1), int(x2), int(y2)
#     cv2.rectangle(threshold, (x1, y1), (x2, y2), 0, 1)
#     cv2.putText(gray, char, (x1, y1 + 20), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 0, 0), 2)

# print(pytesseract.image_to_data(threshold, config=custom_config))

# cv2.imwrite("boxed_characters.jpg", threshold)


